### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by zerothi** [sozykinsa/GUI4dft#1]
This looks very cool! Thanks for sharing this!

Where is the documentation on how to use it, and/or extend it?

Also, why not use sisl to read in the siesta data + special attributes?
I know this may be difficult on windows boxes but for unix + macos?

PS. I am the author of sisl.

**Comment by sozykinsa** [comment]
Hello! Praise from you is a great honor for me. sisl is a very powerful tool!

I am still working on the documentation. The main features of the program are described in the article https://doi.org/10.1016/j.cpc.2021.107843. Over time, I plan to write a more complete guide.

Using sisl to read data is a great idea. Perhaps in the future I will do just that.

**Comment by zerothi** [comment]
Thanks.

Yeah, I saw your paper (which directed me here ;))

Ok!
