### ISSUE TITLE
<< No band/DOS file to parse >>

### ISSUE THREAD

**Issue by icamps** [sozykinsa/GUI4dft#3]
Hello @sozykinsa ,

First, thank you very much for your program!

I have a question. Which file should I load in order to get the bands/dos or even the optimization evolution? Loading the OUT file returns "File format error. The format of this file is not supported".

I am calling GUI4DFT from inside the folder were the SIESTA output files are. The installation files of GUI4DFT are in other folder.

My system is running Ubuntu 21.04 64 bits.

Regards,

Camps

**Comment by sozykinsa** [comment]
Thank you for your interest in my program. You are right and you need to open the OUT file. Please send (here or by e-mail: sozykinsa@susu.ru) me an example of a OUT file that causes the mentioned error.

**Comment by icamps** [comment]
Here is one of the outputs.
[BN+CdM4-1Dlinear.zip](https://github.com/sozykinsa/GUI4dft/files/7041117/BN%2BCdM4-1Dlinear.zip)

**Comment by sozykinsa** [comment]
The problem was that some of the input parameters were not displayed in the input file (for example, MD.TypeOfRun). I rewrote the program a bit and everything should work now. Check the latest version of the program.

I hope you find my program useful.

**Comment by icamps** [comment]
Now it works! Thank you.

Note: I use the info about the calculation parameters in an external file as I have several system, this was the way I found to make no mistake on them.
