### ISSUE TITLE
<< Cell box different from structure >>

### ISSUE THREAD

**Issue by icamps** [sozykinsa/GUI4dft#4]
Hi @sozykinsa ,

I have a nanotube that is centered in a cell. When I visualize the structure and the cell in GUI4DFT, the nanotube appears in a corner, not in the center of the cell.

The images are below; the first one is from GDIS and the second one if from GUI4DFT.

Regards,

Camps
PS: this is the input structure from the other [post](https://github.com/sozykinsa/GUI4dft/issues/3).

![fromGDIS](https://user-images.githubusercontent.com/13273938/130681516-3b096c1c-ccab-430a-b93f-e1f20d2780d9.jpg)
![fromGUI4DFT](https://user-images.githubusercontent.com/13273938/130681520-722ed9d1-ccb5-4578-b752-c9f4a8fe79f0.png)

**Comment by sozykinsa** [comment]
Thank you for your interest in my program.

In most of the files the program works with, the concept of a origin point is absent. So the choice of the position of the cell is a convention. Perhaps you are right and I chose not the most obvious way to select the origin. I made changes to the program. Now everything works as you would like.

There is a button for exporting pictures in my program. The quality is much better than with a "print screen"
![2021-08-25_10-00-07](https://user-images.githubusercontent.com/47054553/130729450-fa2275bc-3b61-47c7-91d1-e1e9b756a45a.png)
.
Sergey Sozykin

**Comment by icamps** [comment]
Dear @sozykinsa ,

The issue with the cell representation is fixed, thanks. I think that for a crystal, the previous implementation could be good, but for artificial 3D systems, it is important to visualize the system as design due to the vacuum space added to the system.

A bad news is that the parsing is broken (I can not import band/DOS files).

Also, I used the SaveFigure3D option in my Linux box, not in the Windows.

Regards,

Camps

**Comment by icamps** [comment]
Hi @sozykinsa ,

Sorry for the delay... Answering your question: using your files works fine. The problem is that my input FDF file has two parts: one with the structure and other one with the calculation parameters.

In my previous [comment](https://github.com/sozykinsa/GUI4dft/issues/3), you fixed this issue :) but now, fixing the issue with cell representation, the error went back :(.

**Comment by sozykinsa** [comment]
I added support for parsing included files.
However, it is not clear to me why the program did not work for you. Only the SystemLabel variable is used to find additional files. You had it in the file with coordinates. Maybe you overridden it in the included file? 
If my revision did not help you, please send examples of your files.

**Comment by icamps** [comment]
Hi @sozykinsa I just re-install GUI4dft from zero, reboot the computer and now is working fine. Thanks.
