### ISSUE TITLE
<< Community help >>

### ISSUE THREAD

**Issue by icamps** [sozykinsa/GUI4dft#6]
Hello @sozykinsa ,

I am moderator of the Matter Modeling Stack Exchange forum.

There is a question related to the development of GUI for quantum computational software. I think that your experience can help the forum users.

The question is: [https://mattermodeling.stackexchange.com/q/7065/24](https://mattermodeling.stackexchange.com/q/7065/24)

Sorry to use this way to be in contact with you. Please, delete the post ASAP.

Thank you.

Camps

**Comment by sozykinsa** [comment]
Thank you for the link to an interesting discussion.
